import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { Fetcher } from "swr";
import { IEventModel } from "../models/IEventModel";
import axiosIns from "../api/axios";
import { Stack, Box } from "@mui/material";
import { AddEvent } from "../components/AddEvent";
import { Events } from "../components/Events";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Stack direction={"row"}>
          <Box component={"section"} sx={{ m: 2, width: "30%" }}>
            <Events />
          </Box>
          <Box
            component={"section"}
            sx={{
              p: 2,
              width: "30%",
              borderLeft: "1px dotted",
            }}
          >
            <AddEvent />
          </Box>
        </Stack>
      </main>
    </div>
  );
}
